// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 Tobias Sarnowski

//! Specification test runner.
//!
//! This module runs tests extracted from the Lonala specification documents.
//! Tests are embedded as static data generated by extract_spec_tests.py.
//!
//! ## Output Format
//!
//! Results are printed as JSON lines to stdout. Each line is self-contained
//! with all information needed for reporting (no external JSON file required):
//!
//! ```json
//! {"source_file":"docs/lonala/lona.core.md","source_line":183,"status":"pass","actual":"3","expected":"3","expr":"(+ 1 2)","tags":[]}
//! {"source_file":"docs/lonala/lona.core.md","source_line":181,"status":"fail","actual":"type error","expected":"0","expr":"(+)","tags":["todo"]}
//! ```

use crate::compiler;
use crate::platform::MemorySpace;
use crate::process::{Process, WorkerId};
use crate::reader::read;
use crate::realm::Realm;
use crate::scheduler::Worker;
use crate::term::printer::print_term;
use crate::uart::Uart;
use crate::vm;

use super::spec_data::{self, ExpectedType, SPEC_BLOCKS};
use super::tests_basic::OutputBuffer;

/// Run all specification tests and output results as JSON lines.
///
/// Returns the number of tests that are real failures (implementation bugs).
/// Tests marked with @todo that fail as expected do NOT count as failures.
/// Tests marked with @todo that pass unexpectedly DO count as failures (stale @todo).
pub fn run_spec_tests<M: MemorySpace, U: Uart>(
    proc: &mut Process,
    realm: &mut Realm,
    mem: &mut M,
    _uart: &mut U,
) -> u32 {
    sel4::debug_println!("=== SPEC TEST RUN ===");

    let total_assertions: usize = SPEC_BLOCKS.iter().map(|b| b.assertions.len()).sum();
    sel4::debug_println!(
        "Loaded {} test blocks with {} assertions",
        SPEC_BLOCKS.len(),
        total_assertions
    );

    let mut worker = Worker::new(WorkerId(0));

    // Track 4 categories:
    // - passed: tests without @todo that pass (good)
    // - failed: tests without @todo that fail (implementation bug)
    // - todo_expected: tests with @todo that fail (expected, pending implementation)
    // - todo_unexpected: tests with @todo that pass (stale @todo, should be removed)
    let mut passed = 0u32;
    let mut failed = 0u32;
    let mut todo_expected = 0u32;
    let mut todo_unexpected = 0u32;

    for block in SPEC_BLOCKS {
        // Filter by architecture (skip blocks that don't match current arch)
        if !should_run_block(block) {
            continue;
        }

        // Run setup lines first
        let mut setup_failed = false;
        for setup in block.setup {
            if let Err(_) = eval_expr(setup.expression, &mut worker, proc, realm, mem) {
                // Setup failure - skip entire block
                let source_line = block.line_start + setup.line_offset;
                sel4::debug_println!(
                    "{{\"source_file\":\"{}\",\"source_line\":{},\"setup_error\":true}}",
                    block.source_file,
                    source_line
                );
                setup_failed = true;
                break;
            }
        }

        if setup_failed {
            // Count setup failures based on whether block has @todo
            let block_is_todo = block.block_tags.iter().any(|t| *t == "todo");
            if block_is_todo {
                todo_expected += block.assertions.len() as u32;
            } else {
                failed += block.assertions.len() as u32;
            }
            // Reset process state even on setup failure to prevent accumulation
            worker.reset_x_regs();
            proc.reset();
            proc.reset_heap();
            continue;
        }

        // Run assertions
        for assertion in block.assertions {
            // Skip assertions that don't match current architecture
            if !should_run_assertion(block, assertion) {
                continue;
            }

            let result = eval_and_capture(assertion.expression, &mut worker, proc, realm, mem);

            let (pass, actual_str): (bool, &str) = match &result {
                Ok(output_buf) => {
                    let actual = output_buf.as_str().unwrap_or("ERROR");
                    match assertion.expected_type {
                        ExpectedType::Value => {
                            if let Some(expected_value) = assertion.expected_value {
                                let eq = str_eq(actual, expected_value);
                                (eq, actual)
                            } else {
                                (false, actual)
                            }
                        }
                        ExpectedType::Error => {
                            // Expected an error but got a value
                            (false, actual)
                        }
                    }
                }
                Err(e) => {
                    match assertion.expected_type {
                        ExpectedType::Error => {
                            // Got an error as expected - check type if specified
                            let actual_error = e.as_str();
                            let pass = if let Some(expected_type) = assertion.expected_value {
                                // Use str_eq for alignment safety on x86_64
                                str_eq(expected_type, actual_error)
                            } else {
                                // No specific type expected, any error passes
                                true
                            };
                            (pass, actual_error)
                        }
                        ExpectedType::Value => {
                            // Expected a value but got an error
                            (false, e.as_str())
                        }
                    }
                }
            };

            // Check if this test is marked @todo (from block or assertion tags)
            let is_todo = block.block_tags.iter().any(|t| *t == "todo")
                || assertion.tags.iter().any(|t| *t == "todo");

            // Print JSON result line with all info needed for reporting
            let expected_str = assertion.expected_value.unwrap_or("ERROR");
            let source_line = block.line_start + assertion.line_offset;
            let status = if pass { "pass" } else { "fail" };

            // Build tags JSON array (combine block and assertion tags)
            let tags_json = format_tags(block.block_tags, assertion.tags);
            sel4::debug_println!(
                "{{\"source_file\":\"{}\",\"source_line\":{},\"status\":\"{}\",\"actual\":\"{}\",\"expected\":\"{}\",\"expr\":\"{}\",\"tags\":{}}}",
                block.source_file,
                source_line,
                status,
                escape_json(actual_str),
                escape_json(expected_str),
                escape_json(assertion.expression),
                tags_json
            );

            // Categorize the result
            match (pass, is_todo) {
                (true, false) => passed += 1,         // Test passes (good)
                (false, false) => failed += 1,        // Test fails (implementation bug)
                (false, true) => todo_expected += 1,  // @todo test fails (expected)
                (true, true) => todo_unexpected += 1, // @todo test passes (remove @todo!)
            }
        }

        // Reset process state between blocks
        worker.reset_x_regs();
        proc.reset();
        // Reset heap to prevent exhaustion across many test blocks
        proc.reset_heap();
    }

    // Report summary with all categories
    sel4::debug_println!(
        "=== SPEC RESULTS: {} passed, {} pending, {} failed, {} stale-todo ===",
        passed,
        todo_expected,
        failed,
        todo_unexpected
    );

    // Return count of real failures:
    // - failed: tests that should pass but don't (implementation bug)
    // - todo_unexpected: tests marked @todo that now pass (stale marker)
    failed + todo_unexpected
}

/// Error type for spec test evaluation.
///
/// All error types are represented as keywords (e.g., `:syntax-error`)
/// to match the specification format.
enum EvalError {
    Parse(&'static str),
    Compile(&'static str),
    Runtime(&'static str),
}

impl EvalError {
    fn as_str(&self) -> &'static str {
        match self {
            EvalError::Parse(kind) => kind,
            EvalError::Compile(kind) => kind,
            EvalError::Runtime(kind) => kind,
        }
    }
}

/// Evaluate an expression and return the result in an OutputBuffer.
fn eval_and_capture<M: MemorySpace>(
    expr_str: &str,
    worker: &mut Worker,
    proc: &mut Process,
    realm: &mut Realm,
    mem: &mut M,
) -> Result<OutputBuffer, EvalError> {
    use crate::compiler::CompileError;
    use crate::vm::RuntimeError;

    // Parse
    let expr = match read(expr_str, proc, realm, mem) {
        Ok(Some(v)) => v,
        Ok(None) => return Err(EvalError::Parse(":parse-error")),
        Err(_) => return Err(EvalError::Parse(":parse-error")),
    };

    // Compile
    let chunk = match compiler::compile(expr, proc, mem, realm) {
        Ok(c) => c,
        Err(e) => {
            let kind = match e {
                CompileError::UnboundSymbol => ":undefined",
                CompileError::InvalidSyntax => ":syntax-error",
                CompileError::TooManyArguments => ":too-many-arguments",
                CompileError::IntegerTooLarge => ":integer-too-large",
                CompileError::ConstantPoolFull => ":constant-pool-full",
                CompileError::ExpressionTooComplex => ":expression-too-complex",
                CompileError::InternalError => ":internal-error",
            };
            return Err(EvalError::Compile(kind));
        }
    };

    // Execute
    if !proc.write_chunk_to_heap(mem, &chunk) {
        return Err(EvalError::Runtime(":out-of-memory"));
    }
    let result = match vm::execute(worker, proc, mem, realm) {
        Ok(v) => v,
        Err(e) => {
            worker.reset_x_regs();
            proc.reset();
            let kind = match e {
                RuntimeError::InvalidOpcode(_) => ":invalid-opcode",
                RuntimeError::IpOutOfBounds => ":ip-out-of-bounds",
                RuntimeError::ConstantOutOfBounds(_) => ":constant-out-of-bounds",
                RuntimeError::Intrinsic(ref ie) => {
                    use crate::intrinsics::IntrinsicError;
                    match ie {
                        IntrinsicError::TypeError { .. } => ":type-error",
                        IntrinsicError::DivisionByZero => ":division-by-zero",
                        IntrinsicError::Overflow => ":overflow",
                        IntrinsicError::UnknownIntrinsic(_) => ":unknown-intrinsic",
                        IntrinsicError::OutOfMemory => ":out-of-memory",
                        IntrinsicError::IndexOutOfBounds { .. } => ":index-out-of-bounds",
                    }
                }
                RuntimeError::NoCode => ":no-code",
                RuntimeError::OutOfMemory => ":out-of-memory",
                RuntimeError::NotCallable { .. } => ":not-callable",
                RuntimeError::ArityMismatch { .. } => ":arity-mismatch",
                RuntimeError::CallableArityError { .. } => ":arity-mismatch",
                RuntimeError::CallableTypeError { .. } => ":type-error",
                RuntimeError::StackOverflow => ":stack-overflow",
                RuntimeError::YRegisterOutOfBounds { .. } => ":y-register-out-of-bounds",
                RuntimeError::FrameMismatch { .. } => ":frame-mismatch",
                RuntimeError::Badmatch { .. } => ":badmatch",
                RuntimeError::EvalError => ":eval-error",
                RuntimeError::ProcessLimitReached => ":process-limit",
            };
            return Err(EvalError::Runtime(kind));
        }
    };

    // Capture output
    let mut output = OutputBuffer::new();
    print_term(result, proc, realm, mem, &mut output);

    Ok(output)
}

/// Evaluate an expression without capturing output (for setup lines).
fn eval_expr<M: MemorySpace>(
    expr_str: &str,
    worker: &mut Worker,
    proc: &mut Process,
    realm: &mut Realm,
    mem: &mut M,
) -> Result<(), ()> {
    // Parse
    let expr = match read(expr_str, proc, realm, mem) {
        Ok(Some(v)) => v,
        Ok(None) => return Ok(()),
        Err(_) => return Err(()),
    };

    // Compile
    let chunk = match compiler::compile(expr, proc, mem, realm) {
        Ok(c) => c,
        Err(_) => return Err(()),
    };

    // Execute
    if !proc.write_chunk_to_heap(mem, &chunk) {
        return Err(());
    }
    match vm::execute(worker, proc, mem, realm) {
        Ok(_) => Ok(()),
        Err(_) => {
            worker.reset_x_regs();
            proc.reset();
            Err(())
        }
    }
}

/// Check if a block should run on the current architecture.
fn should_run_block(block: &spec_data::SpecBlock) -> bool {
    let current_arch = current_arch();

    // If block has no arch tags, run on all architectures
    if !block
        .block_tags
        .iter()
        .any(|t| *t == "x86_64" || *t == "aarch64")
    {
        return true;
    }

    // If block has arch tags, check if current arch matches
    block.block_tags.iter().any(|t| *t == current_arch)
}

/// Check if an assertion should run on the current architecture.
fn should_run_assertion(block: &spec_data::SpecBlock, assertion: &spec_data::Assertion) -> bool {
    let current_arch = current_arch();

    // Combine block and assertion tags
    let has_arch_tag = block
        .block_tags
        .iter()
        .chain(assertion.tags.iter())
        .any(|t| *t == "x86_64" || *t == "aarch64");

    if !has_arch_tag {
        return true;
    }

    // Check if any tag matches current arch
    block
        .block_tags
        .iter()
        .chain(assertion.tags.iter())
        .any(|t| *t == current_arch)
}

/// Get the current architecture as a string.
fn current_arch() -> &'static str {
    #[cfg(target_arch = "x86_64")]
    {
        "x86_64"
    }
    #[cfg(target_arch = "aarch64")]
    {
        "aarch64"
    }
    #[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
    {
        "unknown"
    }
}

/// Format combined tags as a JSON array string.
fn format_tags<'a>(block_tags: &'a [&'a str], assertion_tags: &'a [&'a str]) -> TagsJson<'a> {
    TagsJson {
        block_tags,
        assertion_tags,
    }
}

/// Wrapper that formats tags as JSON array when displayed.
struct TagsJson<'a> {
    block_tags: &'a [&'a str],
    assertion_tags: &'a [&'a str],
}

impl<'a> core::fmt::Display for TagsJson<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "[")?;
        let mut first = true;
        for tag in self.block_tags.iter().chain(self.assertion_tags.iter()) {
            if !first {
                write!(f, ",")?;
            }
            write!(f, "\"{}\"", tag)?;
            first = false;
        }
        write!(f, "]")
    }
}

/// Compare two strings byte-by-byte.
///
/// This avoids SIMD-optimized comparisons that may have alignment requirements
/// not met in the seL4 environment (static data may not be properly aligned
/// for SIMD operations on x86_64).
fn str_eq(a: &str, b: &str) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let ab = a.as_bytes();
    let bb = b.as_bytes();
    for i in 0..ab.len() {
        if ab[i] != bb[i] {
            return false;
        }
    }
    true
}

/// Escape a string for JSON output.
/// Uses a fixed-size buffer to avoid alloc.
fn escape_json(s: &str) -> EscapedJson<'_> {
    EscapedJson(s)
}

/// Wrapper that escapes JSON when displayed.
struct EscapedJson<'a>(&'a str);

impl<'a> core::fmt::Display for EscapedJson<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        for c in self.0.chars() {
            match c {
                '"' => write!(f, "\\\"")?,
                '\\' => write!(f, "\\\\")?,
                '\n' => write!(f, "\\n")?,
                '\r' => write!(f, "\\r")?,
                '\t' => write!(f, "\\t")?,
                c if c.is_control() => write!(f, "\\u{:04x}", c as u32)?,
                c => write!(f, "{}", c)?,
            }
        }
        Ok(())
    }
}
