// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright 2026 Tobias Sarnowski

//! Build script for conditional embedding of lona-vm.elf.
//!
//! If the `LONA_VM_ELF` environment variable is set, the VM binary is embedded
//! into the memory manager. This enables single-image boot on platforms without
//! multiboot module support (e.g., aarch64).

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let Ok(out_dir) = env::var("OUT_DIR") else {
        eprintln!("error: OUT_DIR not set");
        std::process::exit(1);
    };
    let embedded_rs = Path::new(&out_dir).join("embedded_vm.rs");

    let code = env::var("LONA_VM_ELF").map_or_else(
        |_| {
            // No embedded VM - generate None
            String::from(
                "/// No embedded VM (`LONA_VM_ELF` not set).\n\
                 pub static EMBEDDED_VM_ELF: Option<&[u8]> = None;\n",
            )
        },
        |vm_path| {
            // Verify the file exists
            assert!(
                Path::new(&vm_path).exists(),
                "LONA_VM_ELF points to non-existent file: {vm_path}"
            );

            // Rerun if the ELF changes
            println!("cargo::rerun-if-changed={vm_path}");

            // Generate code that embeds the binary
            format!(
                "/// Embedded Lona VM ELF binary.\n\
                 ///\n\
                 /// This is generated by build.rs when `LONA_VM_ELF` is set.\n\
                 pub static EMBEDDED_VM_ELF: Option<&[u8]> = Some(include_bytes!({vm_path:?}));\n"
            )
        },
    );

    // Write the generated code
    let Ok(mut file) = fs::File::create(&embedded_rs) else {
        eprintln!("error: Failed to create embedded_vm.rs");
        std::process::exit(1);
    };
    if file.write_all(code.as_bytes()).is_err() {
        eprintln!("error: Failed to write embedded_vm.rs");
        std::process::exit(1);
    }

    // Always rerun if this env var changes
    println!("cargo::rerun-if-env-changed=LONA_VM_ELF");
}
