// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025 Tobias Sarnowski <tobias@sarnowski.cloud>

//! Tests for the `case` special form compiler.
//!
//! Tests cover:
//! - Basic pattern matching (integers, keywords, strings, nil, booleans)
//! - Default clause with `:else`
//! - Invalid patterns (symbols, lists, vectors, maps, floats)
//! - Duplicate pattern detection
//! - Tail position propagation

use lona_core::chunk::Constant;
use lona_core::opcode::{Opcode, decode_bx, decode_op};
use lona_core::symbol;

use super::{TEST_SOURCE_ID, compile_source, compile_with_interner};
use crate::compiler::CompileError;
use crate::compiler::compile;
use crate::error::{Error, Kind as ErrorKind};

// =========================================================================
// Basic Case Compilation
// =========================================================================

#[test]
fn compile_case_integer_patterns() {
    let chunk = compile_source("(case 1 1 :one 2 :two 3 :three)");
    let code = chunk.code();

    // Should have:
    // LoadK R0, K0 (1 - test value)
    // LoadK R1, K1 (1 - pattern)
    // Eq R2, R0, R1
    // JumpIfNot R2, ...
    // LoadK R1, K2 (:one)
    // Move R0, R1
    // Jump ...
    // ... (more patterns)
    // CaseFail R0 (no :else)

    // Verify test value is loaded
    let first_instr = *code.first().expect("code should not be empty");
    assert_eq!(decode_op(first_instr), Some(Opcode::LoadK));

    // Find CaseFail at the end (before Return)
    let last_before_return = code.get(code.len().saturating_sub(2));
    assert!(
        last_before_return.is_some(),
        "should have instruction before return"
    );
    let case_fail_instr = *last_before_return.expect("last_before_return is Some");
    assert_eq!(decode_op(case_fail_instr), Some(Opcode::CaseFail));
}

#[test]
fn compile_case_keyword_patterns() {
    let (chunk, interner) = compile_with_interner("(case :a :a 1 :b 2)");
    let code = chunk.code();

    // Verify we have bytecode (detailed instruction checking is implementation-specific)
    assert!(!code.is_empty(), "should have generated bytecode");

    // Verify the constants include our keywords (stored as Constant::Keyword)
    let keywords: alloc::vec::Vec<_> = chunk
        .constants()
        .iter()
        .filter_map(|c| {
            if let Constant::Keyword(kw_id) = c {
                Some(interner.resolve(*kw_id))
            } else {
                None
            }
        })
        .collect();
    assert!(
        keywords.iter().any(|k| k == "a"),
        "should have keyword constant for :a"
    );
    assert!(
        keywords.iter().any(|k| k == "b"),
        "should have keyword constant for :b"
    );
}

#[test]
fn compile_case_string_patterns() {
    let chunk = compile_source(r#"(case "hello" "hello" 1 "world" 2)"#);
    let code = chunk.code();

    // Verify first instruction loads the test string
    let first_instr = *code.first().expect("code should not be empty");
    assert_eq!(decode_op(first_instr), Some(Opcode::LoadK));
    let const_idx = decode_bx(first_instr);

    // Constant should be the "hello" string
    assert_eq!(
        chunk.get_constant(const_idx),
        Some(&Constant::String(alloc::string::String::from("hello")))
    );
}

#[test]
fn compile_case_nil_pattern() {
    let chunk = compile_source("(case nil nil 1)");
    let code = chunk.code();

    // Verify first instruction loads nil (uses LoadNil opcode, not LoadK)
    let first_instr = *code.first().expect("code should not be empty");
    assert_eq!(decode_op(first_instr), Some(Opcode::LoadNil));

    // The pattern nil should also be present in constants for comparison
    let has_nil = chunk.constants().iter().any(|c| matches!(c, Constant::Nil));
    assert!(has_nil, "should have nil constant for pattern comparison");
}

#[test]
fn compile_case_boolean_patterns() {
    let chunk = compile_source("(case true true 1 false 2)");
    let code = chunk.code();

    // Verify first instruction loads true
    let first_instr = *code.first().expect("code should not be empty");
    // true is loaded via LoadTrue, not LoadK
    assert_eq!(decode_op(first_instr), Some(Opcode::LoadTrue));
}

// =========================================================================
// Default Clause
// =========================================================================

#[test]
fn compile_case_with_else() {
    let chunk = compile_source("(case 1 2 :two :else :default)");
    let code = chunk.code();

    // With :else, there should be NO CaseFail opcode
    let has_case_fail = code
        .iter()
        .any(|&instr| decode_op(instr) == Some(Opcode::CaseFail));
    assert!(
        !has_case_fail,
        "should not have CaseFail when :else is present"
    );
}

#[test]
fn compile_case_else_must_be_last() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 :else :default 2 :two)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("last clause"));
    } else {
        panic!("expected InvalidSpecialForm error");
    }
}

#[test]
fn compile_case_else_needs_result() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 :else)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, .. },
        ..
    })) = result
    {
        assert_eq!(form, "case");
    } else {
        panic!("expected InvalidSpecialForm error");
    }
}

// =========================================================================
// Invalid Patterns
// =========================================================================

#[test]
fn compile_case_rejects_symbol_pattern() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 x 2)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("symbol"));
    } else {
        panic!("expected InvalidSpecialForm error for symbol pattern");
    }
}

#[test]
fn compile_case_rejects_list_pattern() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 (1 2) 3)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("list"));
    } else {
        panic!("expected InvalidSpecialForm error for list pattern");
    }
}

#[test]
fn compile_case_rejects_vector_pattern() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 [1 2] 3)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("vector"));
    } else {
        panic!("expected InvalidSpecialForm error for vector pattern");
    }
}

#[test]
fn compile_case_rejects_map_pattern() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 {:a 1} 3)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("map"));
    } else {
        panic!("expected InvalidSpecialForm error for map pattern");
    }
}

#[test]
fn compile_case_rejects_float_pattern() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 1.5 2)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("float"));
    } else {
        panic!("expected InvalidSpecialForm error for float pattern");
    }
}

// =========================================================================
// Duplicate Detection
// =========================================================================

#[test]
fn compile_case_rejects_duplicate_integer() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 1 :a 1 :b)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("duplicate"));
    } else {
        panic!("expected InvalidSpecialForm error for duplicate pattern");
    }
}

#[test]
fn compile_case_rejects_duplicate_keyword() {
    let interner = symbol::Interner::new();
    let result = compile("(case :x :a 1 :a 2)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("duplicate"));
    } else {
        panic!("expected InvalidSpecialForm error for duplicate pattern");
    }
}

#[test]
fn compile_case_rejects_duplicate_string() {
    let interner = symbol::Interner::new();
    let result = compile(r#"(case "x" "a" 1 "a" 2)"#, TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("duplicate"));
    } else {
        panic!("expected InvalidSpecialForm error for duplicate pattern");
    }
}

// =========================================================================
// Tail Position
// =========================================================================

#[test]
fn compile_case_in_fn_tail_position() {
    // When case is in tail position, results should use TailCall for function calls
    let chunk = compile_source("(fn [] (case 1 1 (recur)))");
    let _code = chunk.code();

    // Find TailCall in the generated code (for the recur call in the case result)
    // The function body is in the constant pool
    if let Some(Constant::Function { bodies, .. }) = chunk.get_constant(0) {
        let body = bodies.first().expect("function should have a body");
        let body_code = body.chunk.code();

        // The recur in the result should be compiled as TailCall
        let has_tail_call = body_code
            .iter()
            .any(|&instr| decode_op(instr) == Some(Opcode::TailCall));
        assert!(
            has_tail_call,
            "case result in tail position should emit TailCall for recursive calls"
        );
    } else {
        panic!("expected Function constant");
    }
}

// =========================================================================
// Error Cases
// =========================================================================

#[test]
fn compile_case_empty() {
    let interner = symbol::Interner::new();
    let result = compile("(case)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, .. },
        ..
    })) = result
    {
        assert_eq!(form, "case");
    } else {
        panic!("expected InvalidSpecialForm error for empty case");
    }
}

#[test]
fn compile_case_odd_clauses() {
    let interner = symbol::Interner::new();
    let result = compile("(case 1 2)", TEST_SOURCE_ID, &interner);
    assert!(result.is_err());

    if let Err(CompileError::Compile(Error {
        kind: ErrorKind::InvalidSpecialForm { form, message },
        ..
    })) = result
    {
        assert_eq!(form, "case");
        assert!(message.contains("followed by"));
    } else {
        panic!("expected InvalidSpecialForm error for odd number of clauses");
    }
}

#[test]
fn compile_case_no_patterns() {
    // Just an expression, no patterns - should work (goes straight to CaseFail)
    let chunk = compile_source("(case 1)");
    let code = chunk.code();

    // Should have CaseFail
    let has_case_fail = code
        .iter()
        .any(|&instr| decode_op(instr) == Some(Opcode::CaseFail));
    assert!(has_case_fail, "case with no patterns should emit CaseFail");
}
